config/routes.rb
PessanhaVidracaria::Application.routes.draw do
 
  resources :servicos do
    collection do 
      get :bascula_seteira
      get :box
      get :espelho
      get :fechamento
      get :janela
      get :porta
      get :quadro
      get :sacada
      get :vidro_comum
    end
  end
  
  resources :fotoscarros
  
  resources :dicas do 
    collection do
      get :limpeza_box
      get :limpeza_vidro
      get :limpeza_espelho
      get :manutencao_box
      get :recomendacoes_box
      get :vantagens_temperado
    end
  end
  
  resources :locais
   
  resources :somos
    
  resources :administracoes do 
     collection do
      get :alterar_deletar
      get :cadastrar
      get :consultar_relatorio
    end
  end
     
  devise_for :usuarios, controllers: { registrations: 'usuarios' }

  resources :usuarios

  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user
    
    if user.tipo == "Administrador"
		  can :manage, :all
		else
	    can :show, :all 
	  end
	end	  
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :rememberable,
  #  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :lockable, 
         :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :nome, :sobrenome, :sexo, :data_nascimento, :telefone, :endereco,
   :complemento, :bairro, :cidade, :estado, :cep, :email, :password, 
   :password_confirmation
   
   validates :nome, :sobrenome, :sexo, :data_nascimento, :telefone, :endereco,
   :bairro, :cidade, :estado, :password_confirmation, presence: true
   validates :email, format:/^.+\@.+\..+$/
   validates :email, uniqueness:true
end

app/controllers/application_controller.rb
# encoding: utf-8

class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do
    redirect_to root_path
    
    if usuario_signed_in?
      flash[:notice] = 'Você não tem acesso a esta página'
    else
      flash[:notice] = 'Você precisa está cadastrado ou logado'
    end
    
  end
  
  def current_user
    current_usuario
  end
end

app/controllers/dicas_controller.rb
class DicasController < ApplicationController 
 
  def index 
	end 
end

app/controllers/fotoscarros_controller.rb
class FotoscarrosController < ApplicationController 
 
  def index 
	end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
 
  def index 
	end 
end

app/controllers/locais_controller.rb
class LocaisController < ApplicationController 

  def index 
  
  end
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController 
 
  def index 
	end 
end

app/controllers/somos_controller.rb
class SomosController < ApplicationController 

  def index 
	end 
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario cadastrado com sucesso.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def opcoes_para_data
    {size: 10, maxlength: 10, onkeypress: 'return mascaraData(this, event);'}
  end

  def opcoes_para_cpf
    { size: 14, maxlength: 14, onkeypress: 'return mascaraCPF(this, event);'}
  end

  def opcoes_para_telefone
    { size: 14, maxlength: 14, onkeypress: 'return mascaraTelefone(this, event);'}
  end

  def opcoes_para_cep
    { size: 9, maxlength: 9, onkeypress: 'return mascaraCEP(this, event);'}
  end

  def opcoes_para_observacao
    { cols: '33', rows: '5'}
  end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/dicas/index.html.erb
<div id="conteudodica">
  	<h3>Dicas</h3>
						
		<p>A J. Pessanha Vidracaria pensando em nossos clientes e amigos elaborou umas dicas para ajudar na limpeza de box, espelhos, vidros Comuns. Elaborou também recomendações de box, manutenção de box e vantagens dos vidros temperados. Leia com atenção as dicas para ter sucesso com o conteúdo.</p>

    <ol>
      <li><%= link_to 'Limpeza Box', limpeza_box_dicas_path %></li>
      <li><%= link_to 'Limpeza Vidro Comum', limpeza_vidro_dicas_path %></li>
      <li><%= link_to 'Limpeza Espelho', limpeza_espelho_dicas_path %></li>
      <li><%= link_to 'Manutenção Box', manutencao_box_dicas_path %></li>
      <li><%= link_to 'Recomendações box', recomendacoes_box_dicas_path %></li>
      <li><%= link_to 'Vantagens Vidro Temperado', vantagens_temperado_dicas_path %></li>
    </ol>

<%= link_to '', root_path, :class => "voltar" %>

</div>


 

app/views/dicas/limpeza_box.html.erb
<div id="conteudodica">
  <div id="limpa_box">
					
					<h3 class="limpa_box">Limpeza de Box</h3>
						
					 <p>Uma das dúvidas dos nossos clientes é de como limpar um box, por isso vamos tirar algumas dessas dúvidas.</p>
							<ol>
								  <li>Não use produtos abrasivos, como lixa, palha de aço, etc;</li>

								  <li>Não use acidos;</li>
								  <li>Não use facas ou objetos pontiagudos para retirar as etiquetas;</li>
								  <li>Use somente água, sabão ou detergente neutro ou produtos específicos para limpeza de vidro;</li>
								  <li>A permanência de gotas de água após o banho pode, eventualmente, provocar manchas d`água;</li>
								  <li>Portanto remova-as mantendo o box seco e limpo;</li>
							</ol>
							
							
					<h2 class="limpa_box"> Recomendações</h2>

							<ol>
								  <li>Evite o choque de materiais rígidos contra o vidro;</li>
								  <li>Evite impactos violentos na abertura ou fechamento da(s) porta(s);</li>
								  <li>Não deixa crianças desacompanhada utilizarem o box;</li>
							</ol>
							
<%= link_to '', dicas_path, :class => "voltar" %>

</div>							
</div>
				
 

app/views/dicas/limpeza_espelho.html.erb
<div id="conteudodica">
						<h3 class="limpa_espelho">Limpeza de Espelho</h3>
							
						<p>Uma das dúvidas dos nossos clientes é de como limpar um espelho, por isso vamos tirar algumas dessas dúvidas.</p>
						
						<ol>
							  <li>Limpe o espelho com água morna, aplicado com pano. É o procedimento mais simples e seguro, mas tenha cuidado para não deixar que as bordas do espelho permaneçam úmidas após a conclusão da limpeza;</li>

							  <li>Nunca use produtos ácidos ou alcalinos para limpeza do espelho após sua instalação. Esses produtos podem atacar e comprometer a superfície, as bordas e até o revestimento posterior do espelho.Nunca use produtos de limpeza abrasivo (lixas por exemplo) em qualquer superfície do espelho;</li>

							  <li>Ao limpar o espelho, use sempre panos macios e isentos apoeira, para reduzir as chances de riscar sua superfície;</li>

							  <li>Fique atento para a secagem total de todas as juntas e bordas do espelho. Certifique-se de que nenhum resíduo de produtos de limpeza tenha permanecido em contato com a borda ou com o revestimento posterior do espelho;</li>

							  <li>Um ambiente ventilado inibe a condensação de umidade, que pode ser corrosiva e prejudicial à conservação do espelho;</li>

						</ol>
						
	<%= link_to '', dicas_path, :class => "voltar" %>
</div>
				

app/views/dicas/limpeza_vidro.html.erb
<div id="conteudodica">
  <div id="limpa_vidro">
					<h3 class="limpa_vidro">Limpeza de Vidro Comum</h3>
						
					<p>Uma das dúvidas dos nossos clientes é de como limpar um vidro, por isso vamos tirar algumas dessas dúvidas.</p>

					<br><br>
					
					<h3 class="limpa_vidro2">Vidros Comuns</h3>

					<ol>
						  <li>Para limpeza de rotina, use três colheres de vinagre diluídas em 11 litros de água quente.</li>
						  <li>Se o vidro estiver muito sujo, primeiro limpe o com água e sabão.</li>
						  <li>Para secar superfícies, utilize tecido de algudão reutilizado ou jamais velhos.</li>

					</ol>

					<br>
					
					<h3 class="limpa_vidro3">Vidros Cristal</h3>
					
					<ol>
						<li>Pano macio umidecido com álcool ou limpa vidro.</li>
					</ol>
					
<%= link_to '', dicas_path, :class => "voltar" %>

</div>
</div>

app/views/dicas/manutencao_box.html.erb
<div id="conteudodica">
					<h3 class="manutencao_box">Manutenção de Box </h3>
						
					 <p>Se o box apresentar qualquer irregularidade, seu uso deve ser interrompido imediatamente e o mesmo deve ser submetido à manutenção.</p>

					<ol>
					  <li>Porta abrindo ou fechando com dificuldade;</li>

					  <li>Guia da porta quebrada ou com flexibilidade excessiva;</li>

					  <li>Batedores inferior ou superior quebrados e/ou soltos;</li>

					  <li>Contato com o puxador com o outro vidro;</li>

					  <li>Trava de segurança;</li>

					  <li>Excesso no conjunto box, etc.</li>

					</ol>

					<p>* Mesmo que seu box não apresente nenhuma irregularidade, faça a manutenção preventiva a cada 12 meses.</p>


<%= link_to '', dicas_path, :class => "voltar" %>

</div>

app/views/dicas/recomendacoes_box.html.erb
<div id="conteudodica">
  <div id="recomendacoes_box">
				
					<h3 class="recomendacoes_box">Recomendações para Box</h3>
						
						 <ol>
							  <li>Só utilize seu Box após 24h da instalação, pois esse é o período necessário para a completa secagem do silicone.</li>

							  <li>É necessário que seja feita a revisão do produto a cada 12 meses, para garantir seu bom funcionamento.</li>

							  <li>Use somente água e sabão neutro para efetuar a limpeza do vidro e mantenha o Box sempre limpo e seco, pois resíduos de shampoo, sabão, etc podem manchá-lo.</li>

							  <li>Não deixe crianças desacompanhadas utilizarem o Box.</li>

							  <li>Evite impactos violentos na abertura ou fechamento das portas.</li>

							  <li>Nunca troque o puxador original do Box Blindex por um de mercado.</li>

							  <li>Evite impactos com materiais rígidos, como: metal, mármore, azulejos, granito.</li>

							  <li>Prepare o banheiro para receber a instalação do Box, deixando-o seco e tendo em mãos a planta do projeto hidráulico, evitando assim que sejam feitos furos em locais por onde passa o encanamento.</li>

						</ol>
						
<%= link_to '', dicas_path, :class => "voltar" %>

</div>
</div>

app/views/dicas/vantagens_temperado.html.erb
<div id="conteudodica">
					<h3 class="vantagens_temper">Vantagens de um Vidro Temperado</h3>
						
					<p>O vidro temperado quando fraturado se fragmenta em pequenos pedaços, com arestas menos cortantes que o vidro comum. Tem resistência mecânica cerca de quatro a cinco vezes superiores do vidro comum.</p>

					<p>O processo de fabricação do vidro temperado consiste no aquecimento da matéria-prima (cristal ou vidro impresso) submetido a um tratamento térmico de têmpera à temperatura de 650/700ºC, recebendo logo após, choque térmico provocado por jatos de ar. Esta brusca mudança de temperatura gera uma compressão das faces externas e expansão na parte interna, adquirindo neste processo características de resistência muito maior do que as do vidro comum.</p>

					<h3 class="vantagens_temper2"> Onde o vidro temperado é indicado ?</h3>

					<p>O vidro temperado é indicado para locais que requerem resistência, como boxes de chuveiro, portas de vidro ou frontões de lareira, seu uso em fachadas está restrito a entre vãos de pequenas dimensões dentro de caixilhos.</p>

					<p>O vidro temperado oferece segurança por evitar ferimentos graves ao ser quebrado devido a seus pequenos fragmentos arredondados, pois possuem furações e recortes especiais que não fragilizam a peça, tendo excelente efeito estético pela ausência de esquadrias, baixo custo comparado com o vidro comum.</p>
					
					<%= link_to '', dicas_path, :class => "voltar" %>
					
</div>

app/views/home/index.html.erb
<% if can? :manage, :all %>
 <div id="menuadminitrador">
	   <%= link_to '', alterar_deletar_administracoes_path, :class => "menualterar" %>
	   <%= link_to '', cadastrar_administracoes_path, :class => "menucadastrar" %>
	   <%= link_to '', consultar_relatorio_administracoes_path, :class => "menuconsultar" %>
	 </div>
		
<% else %>
<div id="home">
<div class="recentes_servicos">
  <div class="projeto_slideshow">  
    <div id="one" class="contentslider">
      <div class="cs_wrapper">
        <div class="cs_slider">
          
          <div class="cs_article">
            <a href="#"><img src="/assets/slide/foto.jpg" alt="Screenshot 1" />
            </a>
          </div>
          
          <div class="cs_article">
            <a href="#"><img src="/assets/slide/foto2.jpg" alt="Screenshot 2" />
            </a>
          </div>
          
          <div class="cs_article">
            <a href="#"><img src="/assets/slide/foto3.jpg" alt="Screenshot 3" />
            </a>
          </div>
          
          <div class="cs_article">
            <a href="#"><img src="/assets/slide/foto4.jpg" alt="Screenshot 4" />
            </a>
          </div>
                    
        </div>
      </div>
    </div>
</div>
            
      <div class="projeto_conteudo">
        <div class="nossos_servicos">Nossos Serviços</div>
          <p>Esses são alguns dos serviços feitos pela nossa empresa. A nossa empresa procura atender todos os nossos clientes com dedicação. Para confirir mais alguns dos nossos serviços, clique no botão abaixo.</p>
          
          <div class="veja_mais"><%= link_to "Veja mais", servicos_path %></div>
        </div>
      </div>
      
            
      <div id="noticia">
      
        <h1>Noticias</h1>
      </div>
      
      <div id= "tabuadecarne">
      
        <img src="/assets/home/tabuadetime.jpg"/>
      
      </div>
      
      
      
      <div id="localizacao">
      
         <%= link_to '', locais_path, :class => "localizacao" %>
        
      </div>
      
      <div id="mural">
      
        <img src="/assets/home/recado.gif"/>
        
      </div>
      
      <div id="dicas">
      
        <%= link_to '', dicas_path, :class => "dicas" %>
        
      </div>
      
      <div id="carro">
      
        <%= link_to '', fotoscarros_path, :class => "carros" %>
        
        <p>A J. Pessanha pensando nos clientes e no melhor para nossos funcionários, inovou muito pintanto o seu carro com desenhos muitos legais, confira as fotos.</p>
        
      </div>
        
        
</div>
      
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>J. Pessanha Vidraçaria - O melhor em vidro</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.easing.1.3.js" %>
  <%= javascript_include_tag "jquery.ennui.contentslider.js" %>
  <%= javascript_include_tag "jquery-1.3.2.min.js" %>
  <%= javascript_include_tag "NFLightBox.js" %>
  
  
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <link rel="shortcut icon" href="/assets/favicon.ico" >
          
   <script type="text/javascript">
        $(function() {
        var settings = { containerResizeSpeed: 350
            };
            $('#gallery a').lightBox(settings);
        });
		</script>
	
	<script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="/assets/jquery.ennui.contentslider.js"></script>
  <script type="text/javascript">
        $(function() {
        $('#one').ContentSlider({
        width : '530px',
        height : '200px',
        speed : 800,
/* easing : 'easeInOutExpo' */
/* easing : 'easeOutQuad' */
         easing : 'easeInOutBack'
        });
        });
  </script>
        
        
        
        
</head>
<body>

<div id="cabecalho_fundo">

	<div id="cabecalho">
    
    	<div id="site_logo"></div>
    	<div id="usuario_logado">
    	
    	  <p class ="dia"><%= Time.now.strftime("%A, %d de %B de %Y") %></p>
    	  <br><br><br>
    	  
    	  <% if usuario_signed_in? %>
				  <p class="ola">Olá</p> <p class="usuarionome"><%= current_usuario.nome %> <%= current_usuario.tipo %></p>
				<% end %>
				
			</div>
    
  </div> 
  
</div>

<div id="menu_fundo">   
    
    <div id="menu">
        <ul>
            		 
            <li> <%= link_to "Inicial",root_path %> </li>
						<li> <%= link_to "Empresa", somos_path %> </li>
						<li><a href="#">Produtos</a></li>
						<li><%= link_to "Serviços", servicos_path %></li>
													  
				  <% if usuario_signed_in? %>
				    <li class="last"><a href="#">Contato</a></li>
				    <li><%= link_to 'Sair', destroy_usuario_session_path, method: :delete %></li>
				  <%else%>
				    <li><a href="#">Contato</a></li>
				    <li><%= link_to "Login", usuario_session_path %></li>
				    <li><%= link_to "Cadastra-se", new_usuario_registration_path, :class => "cadastrar" %></li>
				  <% end %>
        </ul>    	
    </div>
    
</div>
<div id = "conteudo_fundo">
  <div id="conteudo">

        <% if notice %>
             <div id='notice'>
                <h1>Aviso</h1>
                <p><%= notice %></p>
             </div>
          <% end %>

          <% if alert %>
             <div id='alert'>
               <h1>Erro</h1>
               <p><%= alert %></p>
             </div>
          <% end %>

<%= yield %>

  </div>

</div>



<div id="rodape_fundo">

	<div id="rodape">
  
    <div class="direitos">
       Copyright © J. Pessanha Vidraçaria 2011 - 2012. Todos os direitos reservados.
         | Desenvolvido por <a href="http://www.murilomanhaes.com" target="_blank">Murilo Manhães</a>
    </div>
        
  </div> 
</div>

</body>
</html>

app/views/servicos/bascula_seteira.html.erb
<div id="conteudoservico">
						<h3 class="bascula_seteira"> Báscula e Seteira </h3>
						<p> Está são as fotos de serviços feito pela J. Pessanha Vidraçaria.</p>


 <div id="gallery">
						<ul>
						
							<li><a href="/assets/fotos/servico/bascula/foto.jpg" title="Fotos de básculas e seteiras">
							  <img src="/assets/fotos/servico/bascula/foto_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto2.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto2_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto3.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto3_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/bascula/foto4.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto4_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto5.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto5_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/bascula/foto6.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto6_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto7.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto7_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto8.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto8_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto9.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto9_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/bascula/foto10.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto10_editada.jpg" width="100" alt="" />
							</a></li>


							<li><a href="/assets/fotos/servico/bascula/foto11.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto11_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/bascula/foto12.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto12_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/bascula/foto13.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto13_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/bascula/foto14.jpg" title="Fotos de básculas e seteiras">
								<img src="/assets/fotos/servico/bascula/foto14_editada.jpg" width="100" alt="" />
							</a></li>
					</ul>
	</div>


<%= link_to '', servicos_path, :class => "voltar_bascula" %>

</div>

app/views/servicos/espelho.html.erb
<div id="conteudoservico">
						<h3 class= "espelho"> Espelhos </h3>
						<p> Está são as fotos de serviços feito pela J. Pessanha Vidraçaria.</p>


 <div id="gallery">
						<ul>
						
							<li><a href="/assets/fotos/servico/espelho/foto.jpg" title="Fotos de Espelhos">
							  <img src="/assets/fotos/servico/espelho/foto_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/espelho/foto2.jpg" title="Fotos de Espelhos">
								<img src="/assets/fotos/servico/espelho/foto2_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/espelho/foto3.jpg" title="Fotos de Espelhos">
								<img src="/assets/fotos/servico/espelho/foto3_editada.jpg" width="100" alt="" />
							</a></li>
						   	<li><a href="/assets/fotos/servico/espelho/foto4.jpg" title="Fotos de Espelhos">
								<img src="/assets/fotos/servico/espelho/foto4_editada.jpg" width="100" alt="" />
							</a></li>
							<li><a href="/assets/fotos/servico/espelho/foto5.jpg" title="Fotos de Espelhos">
								<img src="/assets/fotos/servico/espelho/foto5_editada.jpg" width="100" alt="" />
							</a></li>
						   	
					</ul>
	</div>


<%= link_to '', servicos_path, :class => "voltar_espelho" %>

</div>

app/views/servicos/index.html.erb
<div id="conteudoservico">
  <h3> Serviços </h3>
	<p>A J. Pessanha Vidracaria pensando em nossos clientes e amigos colocou fotos de serviços feito pela empresa. Vejas todas as fotos e confira a qualidade de nossos serviços.</p><br>
					
    <ol>
		  <li><%= link_to 'Báscula e Seteira', bascula_seteira_servicos_path %></li>
		  <li><%= link_to 'Box', box_servicos_path %></li>
      <li><%= link_to 'Espelho', espelho_servicos_path %></li>
      <li><%= link_to 'Fechamentos', fechamento_servicos_path %></li>
			<li><%= link_to 'Janelas', janela_servicos_path %></li>
			<li><%= link_to 'Portas', porta_servicos_path %></li>
			<li><%= link_to 'Quadros', quadro_servicos_path %></li>
			<li><%= link_to 'Sacadas', sacada_servicos_path %></li>
			<li><%= link_to 'Vidro Comum', vidro_comum_servicos_path %></li>
					</ol>
							

<%= link_to '', root_path, :class => "voltar" %>

</div>


 

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Sexo</th>
    <th>Telefone</th>
    <th>Endereco</th>
    <th>Complemento</th>
    <th>Bairro</th>
    <th>Cidade</th>
    <th>Estado</th>
    <th>Email</th>
    <th>Data nascimento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.nome %></td>
    <td><%= usuario.sobrenome %></td>
    <td><%= usuario.sexo %></td>
    <td><%= usuario.telefone %></td>
    <td><%= usuario.endereco %></td>
    <td><%= usuario.complemento %></td>
    <td><%= usuario.bairro %></td>
    <td><%= usuario.cidade %></td>
    <td><%= usuario.estado %></td>
    <td><%= usuario.email %></td>
    <td><%= usuario.data_nascimento %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>